/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestRouteImport } from './routes/request'
import { Route as BusPassRouteImport } from './routes/bus-pass'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedRoutesRouteImport } from './routes/_authenticated/routes'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedFuelLogsRouteImport } from './routes/_authenticated/fuel-logs'
import { Route as AuthenticatedFeesRouteImport } from './routes/_authenticated/fees'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBusesRouteImport } from './routes/_authenticated/buses'
import { Route as AuthenticatedBusPassesRouteImport } from './routes/_authenticated/bus-passes'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students.$id'
import { Route as AuthenticatedBusesIdRouteImport } from './routes/_authenticated/buses.$id'
import { Route as AuthenticatedAttendanceScanRouteImport } from './routes/_authenticated/attendance.scan'
import { Route as AuthenticatedAttendanceReportsRouteImport } from './routes/_authenticated/attendance.reports'
import { Route as AuthenticatedAttendanceManualRouteImport } from './routes/_authenticated/attendance.manual'

const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const BusPassRoute = BusPassRouteImport.update({
  id: '/bus-pass',
  path: '/bus-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoutesRoute = AuthenticatedRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFuelLogsRoute = AuthenticatedFuelLogsRouteImport.update({
  id: '/fuel-logs',
  path: '/fuel-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeesRoute = AuthenticatedFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusesRoute = AuthenticatedBusesRouteImport.update({
  id: '/buses',
  path: '/buses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusPassesRoute = AuthenticatedBusPassesRouteImport.update({
  id: '/bus-passes',
  path: '/bus-passes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStudentsRoute,
} as any)
const AuthenticatedBusesIdRoute = AuthenticatedBusesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBusesRoute,
} as any)
const AuthenticatedAttendanceScanRoute =
  AuthenticatedAttendanceScanRouteImport.update({
    id: '/scan',
    path: '/scan',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const AuthenticatedAttendanceReportsRoute =
  AuthenticatedAttendanceReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const AuthenticatedAttendanceManualRoute =
  AuthenticatedAttendanceManualRouteImport.update({
    id: '/manual',
    path: '/manual',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/bus-pass': typeof BusPassRoute
  '/request': typeof RequestRoute
  '/attendance': typeof AuthenticatedAttendanceRouteWithChildren
  '/bus-passes': typeof AuthenticatedBusPassesRoute
  '/buses': typeof AuthenticatedBusesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/fuel-logs': typeof AuthenticatedFuelLogsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/routes': typeof AuthenticatedRoutesRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/attendance/manual': typeof AuthenticatedAttendanceManualRoute
  '/attendance/reports': typeof AuthenticatedAttendanceReportsRoute
  '/attendance/scan': typeof AuthenticatedAttendanceScanRoute
  '/buses/$id': typeof AuthenticatedBusesIdRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/bus-pass': typeof BusPassRoute
  '/request': typeof RequestRoute
  '/attendance': typeof AuthenticatedAttendanceRouteWithChildren
  '/bus-passes': typeof AuthenticatedBusPassesRoute
  '/buses': typeof AuthenticatedBusesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/fuel-logs': typeof AuthenticatedFuelLogsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/routes': typeof AuthenticatedRoutesRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/attendance/manual': typeof AuthenticatedAttendanceManualRoute
  '/attendance/reports': typeof AuthenticatedAttendanceReportsRoute
  '/attendance/scan': typeof AuthenticatedAttendanceScanRoute
  '/buses/$id': typeof AuthenticatedBusesIdRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/bus-pass': typeof BusPassRoute
  '/request': typeof RequestRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRouteWithChildren
  '/_authenticated/bus-passes': typeof AuthenticatedBusPassesRoute
  '/_authenticated/buses': typeof AuthenticatedBusesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fees': typeof AuthenticatedFeesRoute
  '/_authenticated/fuel-logs': typeof AuthenticatedFuelLogsRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/routes': typeof AuthenticatedRoutesRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/attendance/manual': typeof AuthenticatedAttendanceManualRoute
  '/_authenticated/attendance/reports': typeof AuthenticatedAttendanceReportsRoute
  '/_authenticated/attendance/scan': typeof AuthenticatedAttendanceScanRoute
  '/_authenticated/buses/$id': typeof AuthenticatedBusesIdRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/auth'
    | '/bus-pass'
    | '/request'
    | '/attendance'
    | '/bus-passes'
    | '/buses'
    | '/dashboard'
    | '/fees'
    | '/fuel-logs'
    | '/maintenance'
    | '/requests'
    | '/routes'
    | '/staff'
    | '/students'
    | '/attendance/manual'
    | '/attendance/reports'
    | '/attendance/scan'
    | '/buses/$id'
    | '/students/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/auth'
    | '/bus-pass'
    | '/request'
    | '/attendance'
    | '/bus-passes'
    | '/buses'
    | '/dashboard'
    | '/fees'
    | '/fuel-logs'
    | '/maintenance'
    | '/requests'
    | '/routes'
    | '/staff'
    | '/students'
    | '/attendance/manual'
    | '/attendance/reports'
    | '/attendance/scan'
    | '/buses/$id'
    | '/students/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/access-denied'
    | '/auth'
    | '/bus-pass'
    | '/request'
    | '/_authenticated/attendance'
    | '/_authenticated/bus-passes'
    | '/_authenticated/buses'
    | '/_authenticated/dashboard'
    | '/_authenticated/fees'
    | '/_authenticated/fuel-logs'
    | '/_authenticated/maintenance'
    | '/_authenticated/requests'
    | '/_authenticated/routes'
    | '/_authenticated/staff'
    | '/_authenticated/students'
    | '/_authenticated/attendance/manual'
    | '/_authenticated/attendance/reports'
    | '/_authenticated/attendance/scan'
    | '/_authenticated/buses/$id'
    | '/_authenticated/students/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  AuthRoute: typeof AuthRoute
  BusPassRoute: typeof BusPassRoute
  RequestRoute: typeof RequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus-pass': {
      id: '/bus-pass'
      path: '/bus-pass'
      fullPath: '/bus-pass'
      preLoaderRoute: typeof BusPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routes': {
      id: '/_authenticated/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AuthenticatedRoutesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fuel-logs': {
      id: '/_authenticated/fuel-logs'
      path: '/fuel-logs'
      fullPath: '/fuel-logs'
      preLoaderRoute: typeof AuthenticatedFuelLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees': {
      id: '/_authenticated/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AuthenticatedFeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buses': {
      id: '/_authenticated/buses'
      path: '/buses'
      fullPath: '/buses'
      preLoaderRoute: typeof AuthenticatedBusesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bus-passes': {
      id: '/_authenticated/bus-passes'
      path: '/bus-passes'
      fullPath: '/bus-passes'
      preLoaderRoute: typeof AuthenticatedBusPassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/buses/$id': {
      id: '/_authenticated/buses/$id'
      path: '/$id'
      fullPath: '/buses/$id'
      preLoaderRoute: typeof AuthenticatedBusesIdRouteImport
      parentRoute: typeof AuthenticatedBusesRoute
    }
    '/_authenticated/attendance/scan': {
      id: '/_authenticated/attendance/scan'
      path: '/scan'
      fullPath: '/attendance/scan'
      preLoaderRoute: typeof AuthenticatedAttendanceScanRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/_authenticated/attendance/reports': {
      id: '/_authenticated/attendance/reports'
      path: '/reports'
      fullPath: '/attendance/reports'
      preLoaderRoute: typeof AuthenticatedAttendanceReportsRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/_authenticated/attendance/manual': {
      id: '/_authenticated/attendance/manual'
      path: '/manual'
      fullPath: '/attendance/manual'
      preLoaderRoute: typeof AuthenticatedAttendanceManualRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
  }
}

interface AuthenticatedAttendanceRouteChildren {
  AuthenticatedAttendanceManualRoute: typeof AuthenticatedAttendanceManualRoute
  AuthenticatedAttendanceReportsRoute: typeof AuthenticatedAttendanceReportsRoute
  AuthenticatedAttendanceScanRoute: typeof AuthenticatedAttendanceScanRoute
}

const AuthenticatedAttendanceRouteChildren: AuthenticatedAttendanceRouteChildren =
  {
    AuthenticatedAttendanceManualRoute: AuthenticatedAttendanceManualRoute,
    AuthenticatedAttendanceReportsRoute: AuthenticatedAttendanceReportsRoute,
    AuthenticatedAttendanceScanRoute: AuthenticatedAttendanceScanRoute,
  }

const AuthenticatedAttendanceRouteWithChildren =
  AuthenticatedAttendanceRoute._addFileChildren(
    AuthenticatedAttendanceRouteChildren,
  )

interface AuthenticatedBusesRouteChildren {
  AuthenticatedBusesIdRoute: typeof AuthenticatedBusesIdRoute
}

const AuthenticatedBusesRouteChildren: AuthenticatedBusesRouteChildren = {
  AuthenticatedBusesIdRoute: AuthenticatedBusesIdRoute,
}

const AuthenticatedBusesRouteWithChildren =
  AuthenticatedBusesRoute._addFileChildren(AuthenticatedBusesRouteChildren)

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRouteWithChildren
  AuthenticatedBusPassesRoute: typeof AuthenticatedBusPassesRoute
  AuthenticatedBusesRoute: typeof AuthenticatedBusesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeesRoute: typeof AuthenticatedFeesRoute
  AuthenticatedFuelLogsRoute: typeof AuthenticatedFuelLogsRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedRoutesRoute: typeof AuthenticatedRoutesRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRouteWithChildren,
  AuthenticatedBusPassesRoute: AuthenticatedBusPassesRoute,
  AuthenticatedBusesRoute: AuthenticatedBusesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeesRoute: AuthenticatedFeesRoute,
  AuthenticatedFuelLogsRoute: AuthenticatedFuelLogsRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedRoutesRoute: AuthenticatedRoutesRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  AuthRoute: AuthRoute,
  BusPassRoute: BusPassRoute,
  RequestRoute: RequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
